# Generated by Django 5.2.4 on 2025-08-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_prev_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
