# Generated by Django 5.2.4 on 2025-08-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0002_category_img_prev_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
