# Generated by Django 5.2.4 on 2025-08-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0003_remove_productimage_image_productimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
